use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Clone)]
pub struct VuisFile {
    pub Version: String,
    pub Root: VuisDataNode,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct VuisDataNode {
    pub Id: String,
    pub ColorRgba: [f32; 4],
    pub TextColorRgba: Option<[f32; 4]>,
    pub FontFamily: Option<String>,
    pub FontSizePx: Option<f32>,
    pub WidthPx: f32,
    pub HeightPx: f32,
    pub IsImage: bool,
    pub Base64Image: Option<String>,
    pub HasText: bool,
    pub TextContent: Option<String>,
    pub Base64Font: Option<String>,
    pub AnimTargetWidth: f32,
    pub AnimTargetHeight: f32,
    pub AnimTargetX: Option<f32>,
    pub AnimTargetY: Option<f32>,
    pub AnimTargetRotation: Option<f32>,
    pub AnimDuration: f32,
    pub PositionX: f32,
    pub PositionY: f32,
    pub Rotation: f32,
    pub BorderRadiusPx: f32,
    pub BorderWidthPx: f32,
    pub BorderColorRgba: [f32; 4],
    pub IsGradient: bool,
    pub GradientColor1Rgba: [f32; 4],
    pub GradientColor2Rgba: [f32; 4],
    pub IsInput: bool,
    pub IsHidden: bool,
    pub IsBold: bool,
    pub IsItalic: bool,
    pub Placeholder: String,
    pub HasShadow: Option<bool>,
    pub ShadowColorRgba: Option<[f32; 4]>,
    pub ShadowOffsetX: Option<f32>,
    pub ShadowOffsetY: Option<f32>,
    pub ShadowBlur: Option<f32>,
    pub ShadowSpread: Option<f32>,
    pub IsGrid: Option<bool>,
    pub GridColumns: Option<u32>,
    pub GridRows: Option<u32>,
    pub GridColumnGap: Option<f32>,
    pub GridRowGap: Option<f32>,
    pub Children: Vec<VuisDataNode>,
}